style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.com/shackra/goimapnotify
options:
  commits:
    filters:
      Type:
        - new
        - fix
        - chg
        - perf
        - refactor
  commit_groups:
    title_maps:
      new: Features
      fix: Fixes
      chg: Changes
      perf: Performance Improvements
      refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
